spring.application.name=ecom.proj

#spring.datasource.url=jdbc:h2:mem:Patidar
# spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
#spring.datasource.driverClassName=org.h2.Driver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
# spring.datasource.username=postgres
# spring.datasource.password=root
spring.jpa.defer-datasource-initialization=true

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}